name: jd_mall
description: JingDong App

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^2.1.0
  dio: ^3.0.9
  shared_preferences: ^0.5.3+1
  flutter_webview_plugin: ^0.3.0
  #  flutter_inappbrowser: 1.2.1
  event_bus: ^1.1.0
  provider: ^3.0.0+1
  fluttertoast: ^3.1.0
  sqflite: ^1.1.5
  city_pickers: ^0.2.0
  common_utils: ^1.2.1
  flutter_easyrefresh: ^2.1.6
  transparent_image: ^1.0.0
  #  image_picker: 0.6.7+2
  #  barcode_scan: ^3.0.1
  tencent_im_plugin: ^0.2.33
  #  sy_flutter_alipay: ^0.2.1
  #  sy_flutter_wechat: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/



